### packages/domain/src/entities/Assessment.ts
```typescript
/**
 * ============================================================
 * FILE: packages/domain/src/entities/Assessment.ts
 * ============================================================
 */

import { UserRole, VerificationStatus } from '@readycheck/core-types';

export interface AssessmentQuestion {
  id: string;
  text: string;
  options: string[];
  correctOptionIndex: number;
}

export interface UserAssessmentAttempt {
  attemptNumber: number;
  selectedIndexes: number[];
  isCorrect: boolean;
  answeredAt: Date;
}

/**
 * Represents the Verification Gate for a specific task.
 * Assessments ensure the operator understands the "Action Card" before deployment.
 */
export interface AssessmentEntity {
  id: string;
  taskId: string;
  roleScope: UserRole;
  
  // Content generated by AI Configurator
  questions: AssessmentQuestion[];
  
  // Tracking verification for a specific assigned user
  userId: string;
  status: VerificationStatus;
  
  // History and performance
  attempts: UserAssessmentAttempt[];
  maxAttemptsAllowed: number;
  
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Business logic to evaluate an attempt.
 */
export function evaluateAssessmentAttempt(
  assessment: AssessmentEntity,
  selectedIndexes: number[]
): boolean {
  if (selectedIndexes.length !== assessment.questions.length) return false;

  return assessment.questions.every((q, index) => {
    return q.correctOptionIndex === selectedIndexes[index];
  });
}
```
