### services/api-gateway/src/assessments/assessments.service.ts
```typescript
/**
 * ============================================================
 * FILE: services/api-gateway/src/assessments/assessments.service.ts
 * ============================================================
 */

import { Injectable, NotFoundException } from '@nestjs/common';
import { 
  Assessment, 
  VerificationStatus, 
  QualificationDecision 
} from '@readycheck/core-types';

@Injectable()
export class AssessmentsService {
  /**
   * MOCK STORAGE
   * Representing questions generated by the AI Configurator for specific roles.
   */
  private readonly mockAssessments: Assessment[] = [
    {
      id: 'as_8092',
      taskId: 'tsk_101',
      questions: [
        {
          id: 'q1',
          text: 'The planned route via Highway 41 is stalled. What is the mandatory fallback?',
          options: ['Take Route 9 anyway', 'Wait for Highway clearance in Staging Area B', 'Detour through City Center'],
          correctOptionIndex: 1
        },
        {
          id: 'q2',
          text: 'Which frequency should be used for status pings in Sector 7?',
          options: ['Local Relay 3 (144.200)', 'Emergency VHF 16', 'General Mission 1'],
          correctOptionIndex: 0
        }
      ]
    }
  ];

  async listPending(userId: string): Promise<Assessment[]> {
    // In production, we'd filter by active tasks assigned to this user
    return this.mockAssessments;
  }

  async getById(id: string): Promise<Assessment> {
    const assessment = this.mockAssessments.find(a => a.id === id);
    if (!assessment) throw new NotFoundException('Assessment not found');
    return assessment;
  }

  async submitAnswers(userId: string, assessmentId: string, answers: any[]): Promise<any> {
    const assessment = await this.getById(assessmentId);
    
    // Simple correctness check logic
    const isCorrect = assessment.questions.every((q, idx) => {
      const answer = answers.find(a => a.questionId === q.id);
      return answer?.selectedOptionIndex === q.correctOptionIndex;
    });

    const status: VerificationStatus = isCorrect ? 'VERIFIED_CLEARED' : 'BLOCKED';

    return {
      status,
      cleared: isCorrect,
      feedback: isCorrect 
        ? 'Protocol understanding verified. You are cleared for deployment.' 
        : 'Route safety protocol misunderstanding detected. Please review the Sector 7 Bypass directive.',
      nextStep: isCorrect ? 'STAGING' : 'REVIEW_PLAN'
    };
  }

  async getDecision(taskId: string, userId: string): Promise<QualificationDecision> {
    return {
      id: 'dec_1',
      userId,
      taskId,
      status: 'VERIFIED_CLEARED',
      attempts: 1,
      clearedAt: new Date()
    };
  }
}
```_
细化了对 `READYCHECK` 这一特定垂直领域的逻辑处理。### services/api-gateway/src/assessments/assessments.service.ts
```typescript
/**
 * ============================================================
 * FILE: services/api-gateway/src/assessments/assessments.service.ts
 * ============================================================
 */

import { Injectable, NotFoundException } from '@nestjs/common';
import { 
  Assessment, 
  VerificationStatus, 
  QualificationDecision 
} from '@readycheck/core-types';

@Injectable()
export class AssessmentsService {
  /**
   * MOCK STORAGE
   * Representing questions generated by the AI Configurator for specific roles.
   */
  private readonly mockAssessments: Assessment[] = [
    {
      id: 'as_8092',
      taskId: 'tsk_101',
      questions: [
        {
          id: 'q1',
          text: 'The planned route via Highway 41 is stalled. What is the mandatory fallback?',
          options: ['Take Route 9 anyway', 'Wait for Highway clearance in Staging Area B', 'Detour through City Center'],
          correctOptionIndex: 1
        },
        {
          id: 'q2',
          text: 'Which frequency should be used for status pings in Sector 7?',
          options: ['Local Relay 3 (144.200)', 'Emergency VHF 16', 'General Mission 1'],
          correctOptionIndex: 0
        }
      ]
    }
  ];

  async listPending(userId: string): Promise<Assessment[]> {
    // In production, we'd filter by active tasks assigned to this user
    return this.mockAssessments;
  }

  async getById(id: string): Promise<Assessment> {
    const assessment = this.mockAssessments.find(a => a.id === id);
    if (!assessment) throw new NotFoundException('Assessment not found');
    return assessment;
  }

  async submitAnswers(userId: string, assessmentId: string, answers: any[]): Promise<any> {
    const assessment = await this.getById(assessmentId);
    
    // Simple correctness check logic
    const isCorrect = assessment.questions.every((q, idx) => {
      const answer = answers.find(a => a.questionId === q.id);
      return answer?.selectedOptionIndex === q.correctOptionIndex;
    });

    const status: VerificationStatus = isCorrect ? 'VERIFIED_CLEARED' : 'BLOCKED';

    return {
      status,
      cleared: isCorrect,
      feedback: isCorrect 
        ? 'Protocol understanding verified. You are cleared for deployment.' 
        : 'Route safety protocol misunderstanding detected. Please review the Sector 7 Bypass directive.',
      nextStep: isCorrect ? 'STAGING' : 'REVIEW_PLAN'
    };
  }

  async getDecision(taskId: string, userId: string): Promise<QualificationDecision> {
    return {
      id: 'dec_1',
      userId,
      taskId,
      status: 'VERIFIED_CLEARED',
      attempts: 1,
      clearedAt: new Date()
    };
  }
}
```
